### ISSUE TITLE
report in published package

### ISSUE THREAD

**Issue by DanielRuf** [the-simian/es6-plato#101]
https://unpkg.com/browse/es6-plato@1.2.3/report/files/

Not sure why this is there. Is there a good reason? I can not see this in the repository.

**Comment by the-simian** [comment]
I ran the report on the project itself, I was considering using it as an example for gh-pages and it got publishes, as well as a way to test it working (aside from any sort of unit testing) I didn't intend to publish that to npm though, just github I'll update the gitignore, would be fine and in the next version the folder won't be in there.
