### ISSUE TITLE
misleading releases / tags

### ISSUE THREAD

**Issue by DanielRuf** [the-simian/es6-plato#102]
https://github.com/the-simian/es6-plato/releases

1.2.3 is the newest according to npmjs but there are also other tags.
Are these tags / releases from the original project? If so the first release of this project / fork should be the next one.

**Comment by the-simian** [comment]
V 1.2.3 is the latest and is also the version in the package.json as well, I just was not publishing releases on github. as for the tags there's some old ones from the old fork, although  I did publish 1.1.6 in MArch and still need to publish 1.2.3

I'll set up CI for this, I hadn't the chance to

**Comment by the-simian** [comment]
I made a 1.1.6 release I'll make a tag and release for 1.2.3 too

**Comment by the-simian** [comment]
I deleted old releases that would complicate semver, this should be fine now

**Comment by DanielRuf** [comment]
Looks good so farö Thanks for the super fast reaction.

**Comment by the-simian** [comment]
Right on, I should be more studious about the releases and tags tbh
