### ISSUE TITLE
Since it is called es6 and I am using es6 syntax why are let and others are not supported?

### ISSUE THREAD

**Issue by garrymann** [the-simian/es6-plato#11]
Hi!

The project seems promising however I cannot make it work on my ES6 code.  I also added 'use strict'; and using ESlint.

```
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (..emitted..\plato.js:30:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

My npm is:
```
  npm: '2.15.9',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '56.1',
  modules: '46',
  node: '4.6.1',
  openssl: '1.0.2j',
  uv: '1.9.1',
  v8: '4.5.103.37',
  zlib: '1.2.8' 
```
*****Update:
updated to node: '7.1.0',
now all I get is NaN everywhere and having issues with .reduce()**
```
Error reading file src\client\application.js:  TypeError: (options.globals || []).reduce is not a function
TypeError: (options.globals || []).reduce is not a function
    at new Config (\node_modules\eslint\lib\config.js:211:44)
    at CLIEngine.executeOnText (\node_modules\eslint\lib\cli-engine.js:741:28)
    at lint (\node_modules\es6-plato\lib\reporters\eslint\index.js:49:23)
    at Object.process (\node_modules\es6-plato\lib\reporters\eslint\index.js:6:16)
    at processReporter (\node_modules\es6-plato\lib\plato.js:151:31)
    at \node_modules\lodash\lodash.js:4977:15
    at baseForOwn (\node_modules\lodash\lodash.js:3020:24)
    at \node_modules\lodash\lodash.js:4946:18
    at Function.forEach (\node_modules\lodash\lodash.js:9351:14)
    at \node_modules\es6-plato\lib\plato.js:146:7
```

**Comment by nlindley** [comment]
@garrymann PR #10 was merged yesterday that fixes the `let` and `const` issues, but it doesn’t look like it’s been published to NPM yet

I have also seen the issues with reduce. To just get it to run, I removed `options.globals` from https://github.com/eslint/eslint/blob/master/lib/config.js#L211 which probably causes other problems, but it will run.

If I figure out where the eslint issue is coming from, I’ll file an issue in the appropriate repo (unless you get to it first!).

**Comment by garrymann** [comment]
Thanks for the reply. However the issue still persists for es6-plato@1.0.9 here. 

If it helps I could inform you I have just tried the original [plato@1.7.0](https://github.com/es-analysis/plato) and I was successful. So if you don't consider my case as an issue you can pass on it.

**Comment by nlindley** [comment]
1.0.9 is behind master. If you change your package.json to

```
"es6-plato": "git+https://github.com/the-simian/es6-plato.git"
```

you can try out the latest in Node < 6. The eslint bug will still be there.

**Comment by the-simian** [comment]
ok I published the change by @nlindley , just needed to finish my workday first. As for this issue it is referenced to https://github.com/the-simian/es6-plato/issues/9 as well. Basically your node was old (but looks like you figured that out)

~~If you're still getting it, can you open a separate issue for the reduce function? @garrymann~~

edit: I figured it out. Its eslint api change.

**Comment by the-simian** [comment]
Ok quick followup, @garrymann and @nlindley  I know what your problem is with the `globals prop`: see here...

```
let lintRules = {
    'rules': {
        'indent': [
            2, 'tab'
        ],
        'quotes': [
            2, 'single'
        ],
        'semi': [
            2, 'always'
        ],
        'no-console': [1],
        'curly': ['error'],
        'no-dupe-keys': 2,
        'func-names': [1, 'always']
    },
    'env': {
        'es6': true
    },
    'globals': ['require'], //<---------------- that 
    'parserOptions': {
        'sourceType': 'module',
        'ecmaFeatures': {
            'jsx': true,
            'modules': true
        }
    }
};
```

look at the globals property. Basically the eslint api changed at some point. I updated my readme example to reflect this. It used to be an object `{ require: true }`, but now it is an Array `['require']`.

I just pulled down the latest and ran it. Everything is working just fine! Hope that helps :) Feel free to open another issue if you have any problems. Sorry if I took too long to respond, yesterday was pretty busy.

**Comment by garrymann** [comment]
Brilliant! Cheers for that! :)
