### ISSUE TITLE
Support for *.jsx files?

### ISSUE THREAD

**Issue by artursgirons** [the-simian/es6-plato#14]
https://github.com/the-simian/es6-plato/blob/master/lib/plato.js#L115
`jsx?$`

**Comment by the-simian** [comment]
hey @artursgirons , I've not experimented using this with .jsx. Have you tried this? I am willing to accept pull requests

**Comment by artursgirons** [comment]
Jup, just changed that one place (directly in my local mode_modules) and worked like a charm :)

**Comment by the-simian** [comment]
Hey thanks, @artursgirons . Seems like a simple enough fix, then.  Would you be willing to submit a quick PR? if not I can, but that would get it in faster

**Comment by cdawi** [comment]
When are you going to release new version to npm? Are you doing it manually, or have some kind of CI like Travis CI?

**Comment by the-simian** [comment]
I'll check it tonight @dafit1991

**Comment by the-simian** [comment]
@artursgirons /  @dafit1991 oh i forgot to mention that this is all done and published
