### ISSUE TITLE
Globby from Glob

### ISSUE THREAD

**Issue by Announcement** [the-simian/es6-plato#22]
> `Based on glob, but adds a bunch of useful features and a nicer API.`

> Multiple Patterns
> Negated Patterns

I want to exclude things like `my.ponyfill.js` or something like that. from screwing up my extremely restrictive eslint.

**Comment by the-simian** [comment]
Are you asking me to switch from glob to globby? I want to make sure I understand the issue.

**Comment by Announcement** [comment]
Well either that, or add support some sort of way to control file inputs better.

**Comment by the-simian** [comment]
Can you make and test a PR for this? if nothing breaks I'll pull it in.

**Comment by the-simian** [comment]
ok hey I updated this lmk how it goes, @Announcement
