### ISSUE TITLE
untracked dependencies

### ISSUE THREAD

**Issue by Announcement** [the-simian/es6-plato#29]
es6-plato isn't pulling in the required dependencies, so far to get it to run i've had to install
- `eslint`
- `eslint-plugin-react`
- `babel-eslint`
- `eslint-config-defaults`

**Comment by the-simian** [comment]
that's weird I can see at the very least that eslint is sitting right there in the dependencies list...?
```
 "dependencies": {
    "eslint": "^4.1.0", //<---- on master
    "fs-extra": "^4.0.0",
    "glob": "^7.1.1",
    "lodash": "^4.16.6",
    "posix-getopt": "^1.2.0",
    "typhonjs-escomplex": "0.0.12"
  }
```

Are you doing anything special with the library, like using it in a CI environment? @Announcement

**Comment by the-simian** [comment]
I updated deps, that might fix this.
