### ISSUE TITLE
Maintainability > 100

### ISSUE THREAD

**Issue by nikolay** [the-simian/es6-plato#3]
I get this on every file for some reason with v1.0.6.

**Comment by the-simian** [comment]
hey, I noticed this also. 

Here's the short version: I think that's what its supposed to do, but we might want to change it.

Here's the long version: The scale, as-is is from an unbounded negative number to 171. I can probably normalize it to a number from 1-100. I know that in older versions of plato getting something like a 70 was pretty good. You can see here, that's what microsoft does atm: https://blogs.msdn.microsoft.com/codeanalysis/2007/11/20/maintainability-index-range-and-meaning/

This is often called the 'microsoft variant' score. Its a shifted scale. http://www.projectcodemeter.com/cost_estimation/help/GL_halstead.htm
so you can have:

The original formula:
MI = 171 - 5.2 \* ln(V) - 0.23 \* (G) - 16.2 \* ln(LOC)

The derivative used by Microsoft:
MI = MAX(0,(171 - 5.2 \* ln(Halstead Volume) - 0.23 \* (Cyclomatic Complexity) - 16.2 \* ln(Lines of Code))*100 / 171)

I think its just using the old up-to-171 scale, and maybe we should just go to 100 and that's how it is form now on.

Heres an older thread about it on plato:
https://github.com/es-analysis/plato/issues/116

**Comment by the-simian** [comment]
https://github.com/typhonjs-node-escomplex/typhonjs-escomplex/issues/3

**Comment by the-simian** [comment]
Hey! I added an issue for the maintainer   of the main module responsible for complexity calculation ( @typhonrt )to weigh in on. I'd like to hear his thoughts before I implement a particular fix. Also, just a heads up, this module will _eventually_ be pulled into the main plato repo, too. Just keep an eye our for that, and thanks for opening an issue too, @nikolay 

in the meantime you can still use the module, just assume the scale is up to 171.

**Comment by nikolay** [comment]
@the-simian Okay, but the hint states that it's 0-100 when you hover over the ℹ️ button.

**Comment by typhonrt** [comment]
There already is an option to use the Microsoft maintainability index. You need to pass in `options.newmi = true` [here in Plato](https://github.com/the-simian/es6-plato/blob/master/lib/reporters/complexity/index.js#L9).

Apparently walking up the [call stack in Plato](https://github.com/the-simian/es6-plato/blob/master/lib/plato.js#L44) then `options` here should be `options.complexity.newmi = true`. 

If invoking from the CLI then whatever optional parameters will feed the above should work out.

I certainly need to get up better docs for `typhonjs-escomplex`, but as far as options go it should be in parity with the older [escomplex effort](https://github.com/escomplex/escomplex#options).

**Comment by the-simian** [comment]
Hmm yeah, and it looks like I need to improve Plato readout to make it more obvious what the scale is, too. I might just default that thing to `true` anyways. 

Alright, I'll do that and consider that good, but if I want to conditionally show an ℹ️ based on which score was indicated, I'll consider that a separated feature.

**Comment by the-simian** [comment]
alright, its defaulting to 1-100, you can override it in the options.
