### ISSUE TITLE
Could eslint in plato be updated?

### ISSUE THREAD

**Issue by LeonDWong** [the-simian/es6-plato#32]
I use this tool in my project, the library is a great work. But I found that latest eslint version in library is 4.1.0, and its latest version is 4.13.1. When i run plato in my project, it throws error because of the airbnb-base extends in my eslint config file. And it’s working fine when I update eslint to 4.10.0 or above. Could plato update eslint as well? 
Here is the screenshot:
![image](https://user-images.githubusercontent.com/17465046/33872001-f56c2c36-df4f-11e7-8741-88a06dd26b03.png)

**Comment by the-simian** [comment]
hey @LeonDWong , I just now see this. I will update when I can, but if you want it sooner - can you submit a PR?

**Comment by LeonDWong** [comment]
@the-simian Yes, i found that the greenkeeper created a eslint-about branch already, and just pr this branch.)))
https://github.com/the-simian/es6-plato/pull/33

**Comment by the-simian** [comment]
ok its published, @LeonDWong
