### ISSUE TITLE
Can't run es6-plato@1.0.15 in Unix-like OS in cli

### ISSUE THREAD

**Issue by LeonDWong** [the-simian/es6-plato#34]
When update package to 1.0.15(latest for now), i run script `es6-plato -r -d report code-pieces/v1/*` in cli, then it throw the error `env: node\r: No such file or directory`. It seems like problem is caused by difference of line ending between unix-like OS and Windows. After i changed line ending of es-plato.js from Windows to Unix manually in node_modules/.bin folder, the problem be fixed. But package still remains problem, could it be fixed?
[similar issue in github](https://github.com/npm/npm/issues/12371)

My OS: Mac OS Sierra 10.12.6

![image](https://user-images.githubusercontent.com/17465046/34283559-630e82b6-e707-11e7-9d23-523df0726002.png)

**Comment by the-simian** [comment]
hey  @LeonDWong , thanks for the issue, simple enough:  I'll add that prepublish script, that fixes the line endings.

**Comment by the-simian** [comment]
ok I did a bunch of stuff like set `package.json text eol=lf` in .gitattribues. I -think- that should do it? However you'll need to try it out in your particular environment. Let me know how it goes. @LeonDWong

**Comment by LeonDWong** [comment]
@the-simian GJ, it's fixed in version 1.0.16.

**Comment by the-simian** [comment]
Thanks, @LeonDWong really appreciate the followup!!
