### ISSUE TITLE
ESLint use CLIEngine instead of Linter directly

### ISSUE THREAD

**Issue by jfugett** [the-simian/es6-plato#4]
@the-simian 

In the eslint reporter you're using the linter method directly which doesn't allow the use of plugins, parser, and a few other things that you can setup using the CLIEngine then calling executeOnText.

Documentation http://eslint.org/docs/developer-guide/nodejs-api

I'm going to have to work on this over the weekend for work since we're using flowtype, would you be open to a  PR for this change?

Just wanted to double check because it would be a pretty major overhaul to the eslint reporter.

**Comment by jfugett** [comment]
I take that back the changes may not be as extensive as I thought they would be since the engine automatically picks up the eslint config so all of the plugins and everything are automatically added. The current issue I'm having is that the newline is automatically stripped in the source so I'm getting false positives on the new lines being required at the end of file rule.

**Comment by the-simian** [comment]
Hey i don't mind pulling this in.  Thanks for catching that. I'll get it published very soon.

**Comment by the-simian** [comment]
@jfugett its published!

**Comment by jfugett** [comment]
Awesome

**Comment by the-simian** [comment]
@jfugett hey were you having any problems with the tool locating plugins? This seems to have introduced a regression. I might have to revert it.

**Comment by jfugett** [comment]
@the-simian it was able to find mine without any problems from both the .eslintrc and the configuration object. Before I couldn't get it to load plugins at all.

I didn't test extending though any chance that's what is happening?

**Comment by the-simian** [comment]
@jfugett Well it wasn't able to find the plugins and modules, there is a possibility this is due to me testing on a project while using `npm link`. I just wanted to verify it was working correctly for you. I"ll probably try again in a bit but not with a symlinked module, which might have caused the issue. But yeah, it wasnt able to find things like `eslint-plugin-react` and `babel-module`

**Comment by jfugett** [comment]
let me know if you still have issues without the symlink I'd be happy to help track it down
