### ISSUE TITLE
Some settings in custom .eslintrc.json are being ignored

### ISSUE THREAD

**Issue by gorankarlic** [the-simian/es6-plato#41]
It does not use the eslint configuration file ``.eslintrc.json`` from the current working directory for eslint execution.

**Comment by gorankarlic** [comment]
It **does** use ``.eslintrc.json``from the the current working directory for eslint execution, and it can also be specified with the ``-l myeslintrc.json`` command line argument.

It seems that the rule for using double quotes from my ``.eslintrc.json`` gets overridden and it eslint expects single quotes.

Can be fixed by inserting the following at line ``77`` of ``lib/plato.js``
```js
flags.eslint = _.extend({}, flags.eslint, options.jshint.options); 
```

**Comment by the-simian** [comment]
hey @gorankarlic  I can fix this, but if you want to make a PR, I'd be happy to pull it in too I think I can hit this pretty soon - like this afternoon

**Comment by the-simian** [comment]
@gorankarlic , hey is this still an issue for you? I recently published some changes to these lines that might resolve this.

**Comment by the-simian** [comment]
ok I think the recent update fixes this, but if it doesnt, and its still a problem just reopen an issue. I appreciate the report!
