### ISSUE TITLE
ES7 Support

### ISSUE THREAD

**Issue by Nantris** [the-simian/es6-plato#43]
What would be involved in supporting ES7 features like the [optional chaining operator](https://github.com/tc39/proposal-optional-chaining)?

**Comment by the-simian** [comment]
sorry to take to long to reply, I'm not sure offhand, i've actually not really use that feature much

**Comment by the-simian** [comment]
I am basically wrapping na existing tool to generate the complexity metrics from https://github.com/typhonjs-node-escomplex/typhonjs-escomplex

I think that maybe hit that author up, might be best. So I'll close this as I think its there, not here.
