### ISSUE TITLE
Javascript file extension must be js(x)

### ISSUE THREAD

**Issue by alex-pollan** [the-simian/es6-plato#68]
It would be nice to be able to specify the extension used for input files.
Although I get that the standard extension is ``.js`` in our case we used ``.es6`` because we are migrating a big project from old js specification to es6 specification (so we have them side by side) and we chose to use that extension.
I think won't harm to pass that value as an extra argument.

makes sense?

**Comment by the-simian** [comment]
You're basically asking to change the extension of the file glob to some custom argument (not .js, something arbitrary) right?
believe it or not, its just a simple glob : https://github.com/the-simian/es6-plato/blob/master/lib/plato.js#L60


I've honestly never tried globbing another file format besides .js, but if you did - it would grab those files and (I'm assuming) try to parse them. The underlying parser (typhon es6 complex) I think does expect.js files, but I'd need to dig deeper and see.

what happens right now with a non-.js glob? it ignores them, right?

**Comment by alex-pollan** [comment]
I adjusted the code to my needs.
But I did it below in this line:

} else if (file.match(/\.jsx?$/)) {

I extended the regex to accept es6 too

Sorry for not pasting the line number, I'm with my phone :smile:

Do you want me to submit a PR? Two possibilities here:
- hardcoded regex
- accept option for file extension regex, custom function, etc

**Comment by the-simian** [comment]
Yeah hardcoding .es6 is not a good option, the only thing I could see is letting the user override the regex. so a Pr like that is worth considering

**Comment by the-simian** [comment]
also, this might be a silly question .. why don't you use .es6.js on your files in your project? like you don't need to change the last extension, you can still mark the es6 ones though

**Comment by alex-pollan** [comment]
Not at all, it's a fair question.
We didn't do it when we had the chance. It seemed fine at the moment.
It's a set of projects with many files. 
Obviously, we could do it, but we rather not.

**Comment by the-simian** [comment]
@alex-pollan I'm still open to a PR for this. As I thought about it, it might help with the (admitted small number of) people using .mjs and formats like that too.

**Comment by 1000i100** [comment]
https://github.com/the-simian/es6-plato/blob/master/lib/plato.js#L132
```
} else if (file.match(/\.(js|jsx|mjs|es6|ts|tsx)$/)) {
```
Does this will do the tricks or ts is not handled ?

**Comment by the-simian** [comment]
Hey I pulled in a fix for this today! Jsut reopen if its no good. I can't publish immediately so point to the repo if you need it  right this moment

**Comment by the-simian** [comment]
thank you @1000i100 !!!!
