### ISSUE TITLE
maintain 'es-analysis/plato'?

### ISSUE THREAD

**Issue by tomByrer** [the-simian/es6-plato#8]
Seems like they're looking for help:
https://github.com/es-analysis/plato#needs-active-maintainer

If you do, I'd release your version as v2.0 since you have new calculations, etc.

**Comment by the-simian** [comment]
I plan on helping them, but after running a conference I've been working
on. When I merge into main repo, I'll deprecated this. In the meantime use
this and submit issues here, I'm trying to fix problems and make it work
nice.

**Comment by the-simian** [comment]
Just to swing back on this. I've been in contact with the lead maintainer of plato. He's aware of this project, and has allowed me to contribute. I will get this into plato as soon as I can, but as I said..just keep using this fork in the meantime, and when I get it into plato (main), I will add the proper deprecation notice.

I think that's the closest 'fix' we're going to see on this, so for the sake of keeping the issue tracker clean, I'm gonna close this.

Thanks for your feedback @tomByrer . An yeah, I'll almost certainly bump the version to 2.0 at the time of merging- a lot has changed already.
