### ISSUE TITLE
.eslintrc camelcase configuration error

### ISSUE THREAD

**Issue by Taenick** [the-simian/es6-plato#84]
I currently have the following camelcase rule in my .eslintrc file:

`"camelcase": ["error", { "allow": ["^UNSAFE_"] }]`

According to the eslint documentation, this is completely valid: https://eslint.org/docs/rules/camelcase#allow

But when I run es6plato I get the following error: 

`
Error: .eslintrc: Configuration for rule "camelcase" is invalid:
Value {"allow":["^UNSAFE_"]} should NOT have additional properties.
`

Is this intended to happen?

**Comment by the-simian** [comment]
this might be related to the eslint version, you don't by chance have an older one in the project you're using this with?

see this thread comment: https://github.com/eslint/eslint/pull/10783#issuecomment-430065449

This change was in august, too so it might be the version of eslint I'm using too, in which case I can just update the dep.

**Comment by Taenick** [comment]
That project is using eslint 5.14.1, which is the latest version according to the npm package site: https://www.npmjs.com/package/eslint

If that feature was just added in august then maybe updating the eslint in the es6plato module will resolve this.

Let me know if there is anything else I should look at.

**Comment by the-simian** [comment]
@Taenick thanks for the reply, I think you're right lets try that

**Comment by Taenick** [comment]
@the-simian Any chance that you can merge the eslint update pr in? https://github.com/the-simian/es6-plato/pull/83

**Comment by the-simian** [comment]
@Taenick this should be update in 1.1.6

**Comment by Taenick** [comment]
@the-simian  Thank you!
