### ISSUE TITLE
Create new / missing tagged release(s)

### ISSUE THREAD

**Issue by DanielRuf** [the-simian/es6-plato#86]
The last release was some time ago.

See https://github.com/the-simian/es6-plato/compare/v1.3.0...master

**Comment by the-simian** [comment]
@DanielRuf can you elaborate on what you're asking me to do here? the version I have on master is 1.1.5 and the version on npm is also 1.1.5 (npm is up to date with github). So it looks like you're not telling me to publish whats in master now, but asking me to do something else. The link you provided shows this as well at the bottom, so I'm not yet sure what you're pointing out. 

Are you just concerned the last release was a month ago? Can you explain what's actionable to me so I can better understand? Are you experiencing an issue, or a problem building or something?

**Comment by DanielRuf** [comment]
I think you forgot to push the tags with `git push --tags` as these are missing on GitHub. 1.1.3 is the latest here.

**Comment by DanielRuf** [comment]
https://github.com/the-simian/es6-plato/tags

https://github.com/the-simian/es6-plato/releases

**Comment by the-simian** [comment]
@DanielRuf oh ok, weird. I see what you mean now. Yeah I can do that, I didn't even notice the tags weren't there

**Comment by DanielRuf** [comment]
Well, `git push` does not push the tags by default, it's something that I also forget sometimes ;-)

**Comment by the-simian** [comment]
@DanielRuf there's a tagged release now, I'll be modifying my workflow on this to make the tagging automatic. I also updated eslint while I was in there
