### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by paulblyth** [the-simian/es6-plato#9]
Sorry - probably a really n00b issue but running this from the command line gives me:

```
/Users/paul/app/node_modules/es6-plato/lib/reporters/complexity/index.js:77
	let functions = report.methods.concat(allClassMethods(report));
	^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/pblyth/projects/lti-fe-inbox-app/node_modules/es6-plato/lib/plato.js:30:15)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
```

This is my command:

`node_modules/es6-plato/bin/plato -r -d complexity src`

Any ideas?

**Comment by paulblyth** [comment]
Updated to using Node 7 and I get another error with eslint. Leaving this open for now until I find a solution in case someone has already come across this.

**Comment by the-simian** [comment]
thank for openign an issue @paulblyth !

Seeing the first issue, its almost certainly that you are using an older version of node.
`let` support was added in `Node.js 4.x` , so anything older...won't work with this module. I think you discovered hat too when you updated.

That does resolve the _first issue_ so I'm going to close this. as for your other error? Post it as a separate issue if it comes back! I'll help if I can.

**Comment by nlindley** [comment]
Hey, @the-simian. I’m actually seeing this error in Node 4.6.2 and 5.12.0. Everything seems fine in whatever version of V8 is used in >=6. A couple of `'use strict'` statements will probably clean it up. I can probably get you a PR unless you beat me to it.
