### ISSUE TITLE
Upgrade eslint to v6

### ISSUE THREAD

**Issue by estherleah** [the-simian/es6-plato#91]
I am getting the error `Configuration for rule "react/jsx-no-bind" is invalid: Value {"ignoreRefs":true,"allowArrowFunctions":true,"allowFunctions":false,"allowBind":false,"ignoreDOMComponents":true} should NOT have additional properties.` when trying to run this.
This seems to be fixed by upgrading eslint to version 6.
Could you please do this?

**Comment by the-simian** [comment]
all done, see version 1.2.0
