### ISSUE TITLE
Lodash 4.17.11 has a security vulnerability

### ISSUE THREAD

**Issue by jcoyne** [the-simian/es6-plato#94]
https://npmjs.com/advisories/1065

Please upgrade to >=4.17.12

**Comment by the-simian** [comment]
Ok no problem I can do that, thanks

**Comment by malafalabella** [comment]
https://npmjs.com/advisories/1065

Please upgrade to >=4.17.12

When will this be fixed?

**Comment by the-simian** [comment]
I just published the latest, and that's updated along others!
